exports.localization = {
    'en': {
        CHAT_WITH_US: 'Chat with us',
        NAME: 'Name',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Start conversation',
        NEW_MESSAGE: 'New message',
        NO_USERS_ONLINE: 'Currently there are no users online to help you. Leave a message and we will get back to you ASAP! Sorry!',
        CONVERSATION_HISTORY: 'Conversation history',
        JUST_WRITE: 'Just write...',
        PROBLEM_CONNECTING_TO_SERVER: 'We got a problem connecting to the server!',
        ERROR_FILL_ALL_FIELDS: 'Please fill the fields with valid name and email.',
        CONNECTING_TO_SERVER: 'Connecting to the server...',
        SERVER_OFFLINE: 'Server is now offline!',
        USER_IS_TYPING: 'User is typing...',
        UPLOADING_FILE: 'Uploading file',
        ERROR_UPLOADING_FILE: 'Error uploading the file!',
        ATTACH_FILE: 'Attach a file',
        USER_OFFLINE: 'Looks like internet is gone!',
        USER_ONLINE: 'We are back!',
        MUTE: 'Mute conversation',
        CLOSE: 'Close conversation',
        MINIMIZE: 'Minimize conversation',
        TITLE: 'Support',
        POWERED_BY: 'Powered by <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'pt_PT': {
        CHAT_WITH_US: 'Fale connosco',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar conversa',
        NEW_MESSAGE: 'Nova mensagem',
        NO_USERS_ONLINE: 'Desculpe! Neste momento não existem utilizadores online para ajudá-lo. Deixe uma mensagem e tentaremos entrar em contacto o mais rápido possível!',
        CONVERSATION_HISTORY: 'Histórico da conversa',
        JUST_WRITE: 'Escreva aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Ocorreu um problema ao efectuar a ligação ao servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor preencha os campos com um nome e e-mail válido.',
        CONNECTING_TO_SERVER: 'A ligar ao servidor...',
        SERVER_OFFLINE: 'Servidor está desligado!',
        USER_IS_TYPING: 'A escrever...',
        UPLOADING_FILE: 'Anexando ficheiro',
        ERROR_UPLOADING_FILE: 'Erro ao anexar ficheiro!',
        ATTACH_FILE: 'Anexar um ficheiro',
        USER_OFFLINE: 'Parece que a internet foi abaixo!',
        USER_ONLINE: 'Estamos de volta!',
        MUTE: 'Silenciar conversa',
        CLOSE: 'Fechar conversa',
        MINIMIZE: 'Minimizar conversa',
        TITLE: 'Suporte',
        POWERED_BY: 'Desenvolvido por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'de': {
        CHAT_WITH_US: 'Chatten Sie mit uns',
        NAME: 'Name',
        EMAIL: 'E-Mail',
        START_CONVERSATION: 'Starten Sie einen Chat',
        NEW_MESSAGE: 'Neue Nachricht',
        NO_USERS_ONLINE: 'Zur Zeit ist niemand online um Ihnen zu helfen. Hinterlassen Sie eine Nachricht und wir melden uns sobald wie möglich bei Ihnen.',
        CONVERSATION_HISTORY: 'Nachrichtenverlauf',
        JUST_WRITE: 'Hier schreiben...',
        PROBLEM_CONNECTING_TO_SERVER: 'Die Verbindung zum Server ist fehlgeschlagen.',
        ERROR_FILL_ALL_FIELDS: 'Bitte füllen Sie die Felder mit einem Namen und einer gültigen E-Mail Adresse aus.',
        CONNECTING_TO_SERVER: 'Verbinde zum Server...',
        SERVER_OFFLINE: 'Server ist offline.',
        USER_IS_TYPING: 'Benutzer schreibt...',
        UPLOADING_FILE: 'Datei wird hochgeladen',
        ERROR_UPLOADING_FILE: 'Das Hochladen ist fehlgeschlagen',
        ATTACH_FILE: 'Datei hochladen',
        USER_OFFLINE: 'Keine Internetverbindung',
        USER_ONLINE: 'Internetverbindung wieder vorhanden',
        MUTE: 'Chat stummschalten',
        CLOSE: 'Chat schliessen',
        MINIMIZE: 'Chat minimieren',
        TITLE: 'Support',
        POWERED_BY: '<i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'es': {
        CHAT_WITH_US: 'Habla con nosotros',
        NAME: 'Nombre',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar una conversación',
        NEW_MESSAGE: 'Nuevo mensaje',
        NO_USERS_ONLINE: 'Perdon! Actualmente no hay miembros en línea para ayudarle. Deja un mensaje y trataremos de ponernos en contacto lo antes posible!',
        CONVERSATION_HISTORY: 'Historial de la conversación',
        JUST_WRITE: 'Escriba aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Hubo un problema al conectar con el servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor, rellene los campos con un nombre y una dirección de correo electrónico válida.',
        CONNECTING_TO_SERVER: 'Conectando con el servidor...',
        SERVER_OFFLINE: 'Servidor está apagado!',
        USER_IS_TYPING: 'El usuario está escribiendo...',
        UPLOADING_FILE: 'Enviando fichero',
        ERROR_UPLOADING_FILE: 'Error al adjuntar fichero!',
        ATTACH_FILE: 'Adjuntar un fichero',
        USER_OFFLINE: 'La internet se ha ido',
        USER_ONLINE: 'Estamos de vuelta!',
        MUTE: 'Silenciar conversación',
        CLOSE: 'Cerrar conversación',
        MINIMIZE: 'Minimizar conversación',
        TITLE: 'Soporte',
        POWERED_BY: 'Desarrollado por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'fr': {
        CHAT_WITH_US: 'Chattez avec nous',
        NAME: 'Nom',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Démarrez une conversation',
        NEW_MESSAGE: 'Nouveau message',
        NO_USERS_ONLINE: 'Désolé! Actuellement aucun membre en ligne pour vous aider. laissez un message et nous reviendrons vers vous dès que possible!',
        CONVERSATION_HISTORY: 'L\'historique des conversations',
        JUST_WRITE: 'Écrivez ici ...',
        PROBLEM_CONNECTING_TO_SERVER: 'Problème de connexion au serveur!',
        ERROR_FILL_ALL_FIELDS: 'S\'il vous plaît remplir les champs avec un nom et une adresse email valide.',
        CONNECTING_TO_SERVER: 'Connexion au serveur...',
        SERVER_OFFLINE: 'Server est hors ligne!',
        USER_IS_TYPING: 'l\'utilisateur est en train de taper...',
        UPLOADING_FILE: 'Envoi de fichier',
        ERROR_UPLOADING_FILE: 'Une erreur est survenue durant l\'envoi du fichier!',
        ATTACH_FILE: 'Joindre un fichier',
        USER_OFFLINE: 'Pas de connexion internet',
        USER_ONLINE: 'Nous sommes de retour!',
        MUTE: 'Mettre en sourdine',
        CLOSE: 'Fermer la conversation',
        MINIMIZE: 'Réduire la conversation',
        TITLE: 'Soutien',
        POWERED_BY: 'Propulsé par <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'tr': {
        CHAT_WITH_US: 'Bizimle Konuşun',
        NAME: 'Ad',
        EMAIL: 'E-posta',
        START_CONVERSATION: 'Görüşme başlat',
        NEW_MESSAGE: 'Yeni mesaj',
        NO_USERS_ONLINE: 'Şu anda size yardımcı olabilecek çevrimiçi kullanıcı mevcut değil. Lütfen bir mesaj bırakın, size en kısa zamanda dönüş yapacağız. Üzgünüz.',
        CONVERSATION_HISTORY: 'Görüşme Tarihçesi',
        JUST_WRITE: 'Buraya yazın...',
        PROBLEM_CONNECTING_TO_SERVER: 'Sunucuya bağlanırken bir sorun oluştu!',
        ERROR_FILL_ALL_FIELDS: 'Lütfen tüm alanları geçerli bir isim ve e-posta ile doldurun.',
        CONNECTING_TO_SERVER: 'Sunucuya bağlanılıyor...',
        SERVER_OFFLINE: 'Sunucu şu anda çevrimdışı!',
        USER_IS_TYPING: 'Kullanıcı yazıyor...',
        UPLOADING_FILE: 'Dosya sunucuya yükleniyor',
        ERROR_UPLOADING_FILE: 'Sunucuya dosya yüklenirken hata oluştu!',
        ATTACH_FILE: 'Dosya Ekle',
        USER_OFFLINE: 'Görünüşe göre internet gitti!',
        USER_ONLINE: 'Geri geldik!',
        MUTE: 'Görüşmeyi sessize al',
        CLOSE: 'Görüşmeyi kapat',
        MINIMIZE: 'Görüşmeyi aşağıya indir',
        TITLE: 'Destek',
        POWERED_BY: '<i class="prd-icon-btn-prudio"></i> Prud.io ile çalışmaktadır.'
    },
    'ro': {
        CHAT_WITH_US: 'Discută cu noi',
        NAME: 'Nume',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Pornește conversație',
        NEW_MESSAGE: 'Mesaj Nou',
        NO_USERS_ONLINE: 'Momentan nu este online nici un utilizator care să te ajute. Lasă un mesaj și te vom contacta în curând!',
        CONVERSATION_HISTORY: 'Istoric Conversații',
        JUST_WRITE: 'Scrie aici...',
        PROBLEM_CONNECTING_TO_SERVER: 'A apărut o eroare de conectare la server!',
        ERROR_FILL_ALL_FIELDS: 'Completati câmpurile cu name și email valide.',
        CONNECTING_TO_SERVER: 'Se conectează la server...',
        SERVER_OFFLINE: 'Serverul nu este disponibil!',
        USER_IS_TYPING: 'Utilizatorul scrie...',
        UPLOADING_FILE: 'Încărcare fișier',
        ERROR_UPLOADING_FILE: 'Eroare de încărcare a fișierului!',
        ATTACH_FILE: ' Atașază un fișier',
        USER_OFFLINE: 'Conexiune la Internet indisponibilă!',
        USER_ONLINE: 'Ne-am întors!',
        MUTE: 'Fără Sonor',
        CLOSE: 'Închide conversația',
        MINIMIZE: 'Minimizează conversația',
        TITLE: 'Asistență',
        POWERED_BY: 'Dezvoltat de <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'pt_BR': {
        CHAT_WITH_US: 'Fale conosco',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar conversa',
        NEW_MESSAGE: 'Nova mensagem',
        NO_USERS_ONLINE: 'Desculpe! Neste momento não existem usuários online para ajudá-lo. Deixe uma mensagem e tentaremos entrar em contato o mais rápido possível!',
        CONVERSATION_HISTORY: 'Histórico da conversa',
        JUST_WRITE: 'Escreva aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Ocorreu um problema ao efetuar a conexão com o servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor preencha os campos com nome e e-mail válidos.',
        CONNECTING_TO_SERVER: 'Conectando ao servidor...',
        SERVER_OFFLINE: 'Servidor está fora do ar!',
        USER_IS_TYPING: 'O usuário está escrevendo...',
        UPLOADING_FILE: 'Anexando o arquivo',
        ERROR_UPLOADING_FILE: 'Erro ao anexar o arquivo!',
        ATTACH_FILE: 'Anexar um arquivo',
        USER_OFFLINE: 'Parece que a internet caiu!',
        USER_ONLINE: 'Estamos de volta!',
        MUTE: 'Silenciar conversa',
        CLOSE: 'Fechar conversa',
        MINIMIZE: 'Minimizar conversa',
        TITLE: 'Suporte',
        POWERED_BY: 'Desenvolvido por <i class="prd-icon-btn-prudio"></i> Prud.io'
    }
};
