exports.localization = {
    en: {
        CHAT_WITH_US: 'Chat with us',
        NAME: 'Name',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Start conversation',
        NEW_MESSAGE: 'New message',
        NO_USERS_ONLINE: 'Currently there are no users online to help you. Leave a message and we will get back to you ASAP! Sorry!',
        CONVERSATION_HISTORY: 'Conversation history',
        JUST_WRITE: 'Just write...',
        PROBLEM_CONNECTING_TO_SERVER: 'We got a problem connecting to the server!',
        ERROR_FILL_ALL_FIELDS: 'Please fill the fields with valid name and email.',
        CONNECTING_TO_SERVER: 'Connecting to the server...',
        SERVER_OFFLINE: 'Server is now offline!',
        USER_IS_TYPING: 'User is typing...',
        UPLOADING_FILE: 'Uploading file',
        ERROR_UPLOADING_FILE: 'Error uploading the file!',
        ATTACH_FILE: 'Attach a file',
        USER_OFFLINE: 'Looks like internet is gone!',
        USER_ONLINE: 'We are back!',
        MUTE: 'Mute conversation',
        CLOSE: 'Close conversation',
        MINIMIZE: 'Minimize conversation',
        TITLE: 'Support',
        POWERED_BY: 'Powered by <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    pt: {
        CHAT_WITH_US: 'Fale connosco',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar conversa',
        NEW_MESSAGE: 'Nova mensagem',
        NO_USERS_ONLINE: 'Desculpe! Neste momento não existem utilizadores online para ajuda-lo. Deixe uma mensagem e tentaremos entrar em contacto o mais rápido possivel!',
        CONVERSATION_HISTORY: 'Histórico da conversa',
        JUST_WRITE: 'Escreva aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Ocorreu um problema ao efectuar a ligação ao servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor preencha os campos com um nome e e-mail válido.',
        CONNECTING_TO_SERVER: 'A ligar ao servidor...',
        SERVER_OFFLINE: 'Servidor está desligado!',
        USER_IS_TYPING: 'A escrever...',
        UPLOADING_FILE: 'Anexando ficheiro',
        ERROR_UPLOADING_FILE: 'Erro ao anexar ficheiro!',
        ATTACH_FILE: 'Anexar um ficheiro',
        USER_OFFLINE: 'Parece que a internet foi abaixo!',
        USER_ONLINE: 'Estamos de volta!',
        MUTE: 'Silenciar conversa',
        CLOSE: 'Fechar conversa',
        MINIMIZE: 'Minimizar conversa',
        TITLE: 'Suporte',
        POWERED_BY: 'Desenvolvido por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    de: {
        CHAT_WITH_US: 'Chatten Sie mit uns',
        NAME: 'Name',
        EMAIL: 'E-Mail',
        START_CONVERSATION: 'Starten Sie einen Chat',
        NEW_MESSAGE: 'Neue Nachricht',
        NO_USERS_ONLINE: 'Zur Zeit ist niemand online um Ihnen zu helfen. Hinterlassen Sie eine Nachricht und wir melden uns sobald wie möglich bei Ihnen.',
        CONVERSATION_HISTORY: 'Nachrichtenverlauf',
        JUST_WRITE: 'Hier schreiben...',
        PROBLEM_CONNECTING_TO_SERVER: 'Die Verbindung zum Server ist fehlgeschlagen.',
        ERROR_FILL_ALL_FIELDS: 'Bitte füllen Sie die Felder mit einem Namen und einer gültigen E-Mail Adresse aus.',
        CONNECTING_TO_SERVER: 'Verbinde zum Server...',
        SERVER_OFFLINE: 'Server ist offline.',
        USER_IS_TYPING: 'Benutzer schreibt...',
        UPLOADING_FILE: 'Datei wird hochgeladen',
        ERROR_UPLOADING_FILE: 'Das Hochladen ist fehlgeschlagen',
        ATTACH_FILE: 'Datei hochladen',
        USER_OFFLINE: 'Keine Internetverbindung',
        USER_ONLINE: 'Internetverbindung wieder vorhanden',
        MUTE: 'Chat stummschalten',
        CLOSE: 'Chat schliessen',
        MINIMIZE: 'Chat minimieren',
        TITLE: 'Support',
        POWERED_BY: '<i class="prd-icon-btn-prudio"></i> Prud.io'
    }
};
