exports.localization = {
    'en': {
        CHAT_WITH_US: 'Chat with us',
        NAME: 'Name',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Start conversation',
        NEW_MESSAGE: 'New message',
        NO_USERS_ONLINE: 'Currently there are no users online to help you. Leave a message and we will get back to you ASAP! Sorry!',
        CONVERSATION_HISTORY: 'Conversation history',
        JUST_WRITE: 'Just write...',
        PROBLEM_CONNECTING_TO_SERVER: 'We got a problem connecting to the server!',
        ERROR_FILL_ALL_FIELDS: 'Please fill the fields with valid name and email.',
        CONNECTING_TO_SERVER: 'Connecting to the server...',
        SERVER_OFFLINE: 'Server is now offline!',
        USER_IS_TYPING: 'User is typing...',
        UPLOADING_FILE: 'Uploading file',
        ERROR_UPLOADING_FILE: 'Error uploading the file!',
        ATTACH_FILE: 'Attach a file',
        USER_OFFLINE: 'Looks like internet is gone!',
        USER_ONLINE: 'We are back!',
        MUTE: 'Mute conversation',
        CLOSE: 'Close conversation',
        MINIMIZE: 'Minimize conversation',
        TITLE: 'Support',
        POWERED_BY: 'Powered by <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'cn': {
        CHAT_WITH_US: '和我们聊天',
        NAME: '姓名',
        EMAIL: '邮件',
        START_CONVERSATION: '开始对话',
        NEW_MESSAGE: '新消息',
        NO_USERS_ONLINE: '很遗憾，现在没有任何线上用户能帮到你。留下你的信息，我们会尽快回复你！',
        CONVERSATION_HISTORY: '聊天记录',
        JUST_WRITE: '输入中...',
        PROBLEM_CONNECTING_TO_SERVER: '服务器连接错误',
        ERROR_FILL_ALL_FIELDS: '请输入有效的用户名和邮箱',
        CONNECTING_TO_SERVER: '连接服务器中...',
        SERVER_OFFLINE: '与服务器断开',
        USER_IS_TYPING: '用户正在输入中...',
        UPLOADING_FILE: '上传文件',
        ERROR_UPLOADING_FILE: '上传文件出错!',
        ATTACH_FILE: '附件',
        USER_OFFLINE: '失去连接!',
        USER_ONLINE: '已连接!',
        MUTE: '对话静音',
        CLOSE: '关闭对话',
        MINIMIZE: '最小化对话',
        TITLE: '帮助与支持',
        POWERED_BY: '版权所有©<i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'pt_PT': {
        CHAT_WITH_US: 'Fale connosco',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar conversa',
        NEW_MESSAGE: 'Nova mensagem',
        NO_USERS_ONLINE: 'Desculpe! Neste momento não existem utilizadores online para ajudá-lo. Deixe uma mensagem e tentaremos entrar em contacto o mais rápido possível!',
        CONVERSATION_HISTORY: 'Histórico da conversa',
        JUST_WRITE: 'Escreva aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Ocorreu um problema ao efectuar a ligação ao servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor preencha os campos com um nome e e-mail válido.',
        CONNECTING_TO_SERVER: 'A ligar ao servidor...',
        SERVER_OFFLINE: 'Servidor está desligado!',
        USER_IS_TYPING: 'A escrever...',
        UPLOADING_FILE: 'Anexando ficheiro',
        ERROR_UPLOADING_FILE: 'Erro ao anexar ficheiro!',
        ATTACH_FILE: 'Anexar um ficheiro',
        USER_OFFLINE: 'Parece que a internet foi abaixo!',
        USER_ONLINE: 'Estamos de volta!',
        MUTE: 'Silenciar conversa',
        CLOSE: 'Fechar conversa',
        MINIMIZE: 'Minimizar conversa',
        TITLE: 'Suporte',
        POWERED_BY: 'Desenvolvido por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'de': {
        CHAT_WITH_US: 'Chatten Sie mit uns',
        NAME: 'Name',
        EMAIL: 'E-Mail',
        START_CONVERSATION: 'Starten Sie einen Chat',
        NEW_MESSAGE: 'Neue Nachricht',
        NO_USERS_ONLINE: 'Zur Zeit ist niemand online um Ihnen zu helfen. Hinterlassen Sie eine Nachricht und wir melden uns sobald wie möglich bei Ihnen.',
        CONVERSATION_HISTORY: 'Nachrichtenverlauf',
        JUST_WRITE: 'Hier schreiben...',
        PROBLEM_CONNECTING_TO_SERVER: 'Die Verbindung zum Server ist fehlgeschlagen.',
        ERROR_FILL_ALL_FIELDS: 'Bitte füllen Sie die Felder mit einem Namen und einer gültigen E-Mail Adresse aus.',
        CONNECTING_TO_SERVER: 'Verbinde zum Server...',
        SERVER_OFFLINE: 'Server ist offline.',
        USER_IS_TYPING: 'Benutzer schreibt...',
        UPLOADING_FILE: 'Datei wird hochgeladen',
        ERROR_UPLOADING_FILE: 'Das Hochladen ist fehlgeschlagen',
        ATTACH_FILE: 'Datei hochladen',
        USER_OFFLINE: 'Keine Internetverbindung',
        USER_ONLINE: 'Internetverbindung wieder vorhanden',
        MUTE: 'Chat stummschalten',
        CLOSE: 'Chat schliessen',
        MINIMIZE: 'Chat minimieren',
        TITLE: 'Support',
        POWERED_BY: '<i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'es': {
        CHAT_WITH_US: 'Habla con nosotros',
        NAME: 'Nombre',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar una conversación',
        NEW_MESSAGE: 'Nuevo mensaje',
        NO_USERS_ONLINE: 'Perdon! Actualmente no hay miembros en línea para ayudarle. Deja un mensaje y trataremos de ponernos en contacto lo antes posible!',
        CONVERSATION_HISTORY: 'Historial de la conversación',
        JUST_WRITE: 'Escriba aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Hubo un problema al conectar con el servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor, rellene los campos con un nombre y una dirección de correo electrónico válida.',
        CONNECTING_TO_SERVER: 'Conectando con el servidor...',
        SERVER_OFFLINE: 'Servidor está apagado!',
        USER_IS_TYPING: 'El usuario está escribiendo...',
        UPLOADING_FILE: 'Enviando fichero',
        ERROR_UPLOADING_FILE: 'Error al adjuntar fichero!',
        ATTACH_FILE: 'Adjuntar un fichero',
        USER_OFFLINE: 'La internet se ha ido',
        USER_ONLINE: 'Estamos de vuelta!',
        MUTE: 'Silenciar conversación',
        CLOSE: 'Cerrar conversación',
        MINIMIZE: 'Minimizar conversación',
        TITLE: 'Soporte',
        POWERED_BY: 'Desarrollado por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'fr': {
        CHAT_WITH_US: 'Chattez avec nous',
        NAME: 'Nom',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Démarrez une conversation',
        NEW_MESSAGE: 'Nouveau message',
        NO_USERS_ONLINE: 'Désolé! Actuellement aucun membre en ligne pour vous aider. laissez un message et nous reviendrons vers vous dès que possible!',
        CONVERSATION_HISTORY: 'L\'historique des conversations',
        JUST_WRITE: 'Écrivez ici ...',
        PROBLEM_CONNECTING_TO_SERVER: 'Problème de connexion au serveur!',
        ERROR_FILL_ALL_FIELDS: 'S\'il vous plaît remplir les champs avec un nom et une adresse email valide.',
        CONNECTING_TO_SERVER: 'Connexion au serveur...',
        SERVER_OFFLINE: 'Server est hors ligne!',
        USER_IS_TYPING: 'l\'utilisateur est en train de taper...',
        UPLOADING_FILE: 'Envoi de fichier',
        ERROR_UPLOADING_FILE: 'Une erreur est survenue durant l\'envoi du fichier!',
        ATTACH_FILE: 'Joindre un fichier',
        USER_OFFLINE: 'Pas de connexion internet',
        USER_ONLINE: 'Nous sommes de retour!',
        MUTE: 'Mettre en sourdine',
        CLOSE: 'Fermer la conversation',
        MINIMIZE: 'Réduire la conversation',
        TITLE: 'Soutien',
        POWERED_BY: 'Propulsé par <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'tr': {
        CHAT_WITH_US: 'Bizimle Konuşun',
        NAME: 'Ad',
        EMAIL: 'E-posta',
        START_CONVERSATION: 'Görüşme başlat',
        NEW_MESSAGE: 'Yeni mesaj',
        NO_USERS_ONLINE: 'Şu anda size yardımcı olabilecek çevrimiçi kullanıcı mevcut değil. Lütfen bir mesaj bırakın, size en kısa zamanda dönüş yapacağız. Üzgünüz.',
        CONVERSATION_HISTORY: 'Görüşme Tarihçesi',
        JUST_WRITE: 'Buraya yazın...',
        PROBLEM_CONNECTING_TO_SERVER: 'Sunucuya bağlanırken bir sorun oluştu!',
        ERROR_FILL_ALL_FIELDS: 'Lütfen tüm alanları geçerli bir isim ve e-posta ile doldurun.',
        CONNECTING_TO_SERVER: 'Sunucuya bağlanılıyor...',
        SERVER_OFFLINE: 'Sunucu şu anda çevrimdışı!',
        USER_IS_TYPING: 'Kullanıcı yazıyor...',
        UPLOADING_FILE: 'Dosya sunucuya yükleniyor',
        ERROR_UPLOADING_FILE: 'Sunucuya dosya yüklenirken hata oluştu!',
        ATTACH_FILE: 'Dosya Ekle',
        USER_OFFLINE: 'Görünüşe göre internet gitti!',
        USER_ONLINE: 'Geri geldik!',
        MUTE: 'Görüşmeyi sessize al',
        CLOSE: 'Görüşmeyi kapat',
        MINIMIZE: 'Görüşmeyi aşağıya indir',
        TITLE: 'Destek',
        POWERED_BY: '<i class="prd-icon-btn-prudio"></i> Prud.io ile çalışmaktadır.'
    },
    'ro': {
        CHAT_WITH_US: 'Discută cu noi',
        NAME: 'Nume',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Pornește conversație',
        NEW_MESSAGE: 'Mesaj Nou',
        NO_USERS_ONLINE: 'Momentan nu este online nici un utilizator care să te ajute. Lasă un mesaj și te vom contacta în curând!',
        CONVERSATION_HISTORY: 'Istoric Conversații',
        JUST_WRITE: 'Scrie aici...',
        PROBLEM_CONNECTING_TO_SERVER: 'A apărut o eroare de conectare la server!',
        ERROR_FILL_ALL_FIELDS: 'Completati câmpurile cu name și email valide.',
        CONNECTING_TO_SERVER: 'Se conectează la server...',
        SERVER_OFFLINE: 'Serverul nu este disponibil!',
        USER_IS_TYPING: 'Utilizatorul scrie...',
        UPLOADING_FILE: 'Încărcare fișier',
        ERROR_UPLOADING_FILE: 'Eroare de încărcare a fișierului!',
        ATTACH_FILE: ' Atașază un fișier',
        USER_OFFLINE: 'Conexiune la Internet indisponibilă!',
        USER_ONLINE: 'Ne-am întors!',
        MUTE: 'Fără Sonor',
        CLOSE: 'Închide conversația',
        MINIMIZE: 'Minimizează conversația',
        TITLE: 'Asistență',
        POWERED_BY: 'Dezvoltat de <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'pt_BR': {
        CHAT_WITH_US: 'Fale conosco',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Iniciar conversa',
        NEW_MESSAGE: 'Nova mensagem',
        NO_USERS_ONLINE: 'Desculpe! Neste momento não existem usuários online para ajudá-lo. Deixe uma mensagem e tentaremos entrar em contato o mais rápido possível!',
        CONVERSATION_HISTORY: 'Histórico da conversa',
        JUST_WRITE: 'Escreva aqui...',
        PROBLEM_CONNECTING_TO_SERVER: 'Ocorreu um problema ao efetuar a conexão com o servidor!',
        ERROR_FILL_ALL_FIELDS: 'Por favor preencha os campos com nome e e-mail válidos.',
        CONNECTING_TO_SERVER: 'Conectando ao servidor...',
        SERVER_OFFLINE: 'Servidor está fora do ar!',
        USER_IS_TYPING: 'O usuário está escrevendo...',
        UPLOADING_FILE: 'Anexando o arquivo',
        ERROR_UPLOADING_FILE: 'Erro ao anexar o arquivo!',
        ATTACH_FILE: 'Anexar um arquivo',
        USER_OFFLINE: 'Parece que a internet caiu!',
        USER_ONLINE: 'Estamos de volta!',
        MUTE: 'Silenciar conversa',
        CLOSE: 'Fechar conversa',
        MINIMIZE: 'Minimizar conversa',
        TITLE: 'Suporte',
        POWERED_BY: 'Desenvolvido por <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'nl': {
        CHAT_WITH_US: 'Chat met ons',
        NAME: 'Naam',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Begin een gesprek',
        NEW_MESSAGE: 'Nieuw bericht',
        NO_USERS_ONLINE: 'Momenteel zijn er geen gebruikers online om u te helpen. Laat een bericht achter en wij zullen zo snel mogelijk contact met u op! Sorry!',
        CONVERSATION_HISTORY: 'Gespreksgeschiedenis',
        JUST_WRITE: 'Alleen schrijven...',
        PROBLEM_CONNECTING_TO_SERVER: 'We hebben een probleem met de verbinding met de server!',
        ERROR_FILL_ALL_FIELDS: 'Vul de velden met geldige naam en e-mail.',
        CONNECTING_TO_SERVER: 'Verbinden met de server...',
        SERVER_OFFLINE: 'Server is nu offline!',
        USER_IS_TYPING: 'Gebruiker is het typen ...',
        UPLOADING_FILE: 'Uploaden bestand',
        ERROR_UPLOADING_FILE: 'Fout uploaden van het bestand!',
        ATTACH_FILE: 'Bevestig een bestand',
        USER_OFFLINE: 'Het lijkt erop dat internet is weg!',
        USER_ONLINE: 'We zijn terug!',
        MUTE: 'Mute gesprek',
        CLOSE: 'Sluiten gesprek',
        MINIMIZE: 'Minimaliseren gesprek',
        TITLE: 'Ondersteuning',
        POWERED_BY: 'Aangedreven door <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'it': {
        CHAT_WITH_US: 'Chatta con noi',
        NAME: 'Nome',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Inizia la conversazione',
        NEW_MESSAGE: 'Nuovo messaggio',
        NO_USERS_ONLINE: 'Al momento non ci son utenti in linea per poterti aiutare. Lascia un messaggio e saremo da te il prima possibile! Ci scusiamo per il disagio!',
        CONVERSATION_HISTORY: 'Cronologia conversazione',
        JUST_WRITE: 'Scrivi...',
        PROBLEM_CONNECTING_TO_SERVER: 'C\'è stato un problema durante la connessione al server!',
        ERROR_FILL_ALL_FIELDS: 'Completa i campi usando nome ed email validi.',
        CONNECTING_TO_SERVER: 'Connessione al server...',
        SERVER_OFFLINE: 'Il server non è disponibile!',
        USER_IS_TYPING: 'L\'utente sta scrivendo...',
        UPLOADING_FILE: 'Caricamento file',
        ERROR_UPLOADING_FILE: 'Errore durante il caricamento del file!',
        ATTACH_FILE: 'Allega un file',
        USER_OFFLINE: 'Sembra che iternet sia sparito!',
        USER_ONLINE: 'Siamo tornati!',
        MUTE: 'Muta la conversazione',
        CLOSE: 'Chiudi la conversazione',
        MINIMIZE: 'Minimizza la conversazione',
        TITLE: 'Supporto',
        POWERED_BY: 'Creato da <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'pl': {
        CHAT_WITH_US: 'Porozmawiaj z nami',
        NAME: 'Imię',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Rozpocznij rozmowę',
        NEW_MESSAGE: 'Nowa wiadomość',
        NO_USERS_ONLINE: 'Aktualnie nie ma nikogo kto mógłby z Tobą porozmawiać. Zostaw wiadomość a skontaktujemy się z Tobą tak szybko jak to możliwe.',
        CONVERSATION_HISTORY: 'Historia rozmowy',
        JUST_WRITE: 'Napisz...',
        PROBLEM_CONNECTING_TO_SERVER: 'Napotkaliśmy problem łącząc się z serwerem!',
        ERROR_FILL_ALL_FIELDS: 'Prosimy wypełnić pola poprawnym imieniem i e-mailem.',
        CONNECTING_TO_SERVER: 'Łączenie z serwerem...',
        SERVER_OFFLINE: 'Serwer jest aktualnie offline!',
        USER_IS_TYPING: 'Użytkownik pisze...',
        UPLOADING_FILE: 'Przesyłanie pliku',
        ERROR_UPLOADING_FILE: 'Wystąpił błąd podczas przesyłania pliku!',
        ATTACH_FILE: 'Dołącz plik',
        USER_OFFLINE: 'Wygląda na to, że użytkownik stracił połączenie z internetem.',
        USER_ONLINE: 'Jesteśmy z powrotem!',
        MUTE: 'Wycisz rozmowę',
        CLOSE: 'Zakończ rozmowę',
        MINIMIZE: 'Zminimializuj rozmowę',
        TITLE: 'Support',
        POWERED_BY: 'Napędzane przez <i class="prd-icon-btn-prudio"></i> Prud.io'
    },
    'ru': {
        CHAT_WITH_US: 'Поговорите с нами',
        NAME: 'Имя',
        EMAIL: 'E-mail',
        START_CONVERSATION: 'Начать разговор',
        NEW_MESSAGE: 'Новое сообщение',
        NO_USERS_ONLINE: 'В данный момент на связи нет операторов, которые бы помогли Вам. Оставьте, пожалуйста, сообщение и мы свяжемся с Вами при первой же возможности! Примите наши извинения!',
        CONVERSATION_HISTORY: 'История разговоров',
        JUST_WRITE: 'Напишите сообщение...',
        PROBLEM_CONNECTING_TO_SERVER: 'Возникла проблема при соединении с сервером!',
        ERROR_FILL_ALL_FIELDS: 'Пожалуйста, заполните поля, указав Ваше имя и электронную почту.',
        CONNECTING_TO_SERVER: 'Соединяемся с сервером...',
        SERVER_OFFLINE: 'Сервер в данный момент оффлайн!',
        USER_IS_TYPING: 'Пользователь набирает сообщение...',
        UPLOADING_FILE: 'Файл загружается',
        ERROR_UPLOADING_FILE: 'Возникла ошибка при загрузке файла!',
        ATTACH_FILE: 'Прикрепить файл',
        USER_OFFLINE: 'Похоже, интернет пропал!',
        USER_ONLINE: 'Мы снова на связи!',
        MUTE: 'Отключить звук',
        CLOSE: 'Закрыть разговор',
        MINIMIZE: 'Свернуть разговор',
        TITLE: 'Поддержка',
        POWERED_BY: 'Чат работает на <i class="prd-icon-btn-prudio"></i> Prud.io'
    }
};
